create table public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expo_push_token text not null unique check (char_length(expo_push_token) between 20 and 255),
  platform text not null check (platform in ('android', 'ios')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index push_tokens_user_enabled_idx
  on public.push_tokens (user_id, enabled);

alter table public.push_tokens enable row level security;

create policy "Users can manage their push tokens"
on public.push_tokens for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on public.push_tokens from anon, authenticated;
grant select, delete on public.push_tokens to authenticated;
grant all on public.push_tokens to service_role;
grant usage, select on sequence public.push_tokens_id_seq to service_role;

create function public.register_push_token(
  p_expo_push_token text,
  p_platform text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if p_expo_push_token is null or char_length(p_expo_push_token) not between 20 and 255 then
    raise exception 'Invalid Expo push token' using errcode = '22023';
  end if;

  if p_platform is null or p_platform not in ('android', 'ios') then
    raise exception 'Invalid push platform' using errcode = '22023';
  end if;

  insert into public.push_tokens (
    user_id, expo_push_token, platform, enabled, updated_at
  ) values (
    current_user_id, p_expo_push_token, p_platform, true, now()
  )
  on conflict (expo_push_token) do update
  set user_id = excluded.user_id,
      platform = excluded.platform,
      enabled = true,
      updated_at = now();
end;
$$;

revoke all on function public.register_push_token(text, text) from public, anon, authenticated;
grant execute on function public.register_push_token(text, text) to authenticated;

create table public.push_deliveries (
  id bigint generated by default as identity primary key,
  event_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null check (notification_type = 'purchase_completed'),
  expo_push_token text not null,
  expo_ticket_id text,
  status text not null default 'queued' check (
    status in ('queued', 'ticketed', 'delivered', 'failed')
  ),
  error_code text,
  created_at timestamptz not null default now(),
  receipt_checked_at timestamptz,
  unique (event_key, expo_push_token)
);

create index push_deliveries_receipts_idx
  on public.push_deliveries (created_at)
  where status = 'ticketed';

alter table public.push_deliveries enable row level security;
revoke all on public.push_deliveries from anon, authenticated;
grant all on public.push_deliveries to service_role;
grant usage, select on sequence public.push_deliveries_id_seq to service_role;